apiVersion: v1
kind: Service
metadata:
  name: {{ include "calcpy.fullname" . }}-svc
  labels:
    {{- include "calcpy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "calcpy.selectorLabels" . | nindent 4 }}
